In [2]:
import pandas as pd
import numpy as np

In [3]:
#Index
np.array([1,1,1]) + np.array([-1,0,-1])

array([0, 1, 0])

In [4]:
df = pd.read_csv('earthquakes.csv')

In [6]:
df.count()

alert        59
cdi         329
code       9332
detail     9332
dmin       6139
felt        329
gap        6164
ids        9332
mag        9331
magType    9331
mmi          93
net        9332
nst        5364
place      9332
rms        9332
sig        9332
sources    9332
status     9332
time       9332
title      9332
tsunami    9332
type       9332
types      9332
tz         9331
updated    9332
url        9332
dtype: int64

In [11]:
df.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,329.000000,6139.000000,329.000000,6164.000000,9331.000000,93.000000,5364.000000,9332.000000,9332.000000,9.332000e+03,9332.000000,9331.000000,9.332000e+03
mean,2.754711,0.544925,12.310030,121.506588,1.497345,3.651398,19.053878,0.362122,56.899914,1.538284e+12,0.006537,-451.990140,1.538537e+12
std,1.010637,2.214305,48.954944,72.962363,1.203347,1.790523,15.492315,0.317784,91.872163,6.080306e+08,0.080589,231.752571,6.564135e+08
min,0.000000,0.000648,0.000000,12.000000,-1.260000,0.000000,0.000000,0.000000,0.000000,1.537229e+12,0.000000,-720.000000,1.537230e+12
25%,2.000000,0.020425,1.000000,66.142500,0.720000,2.680000,8.000000,0.119675,8.000000,1.537793e+12,0.000000,-540.000000,1.537996e+12
50%,2.700000,0.059050,2.000000,105.000000,1.300000,3.720000,15.000000,0.210000,26.000000,1.538245e+12,0.000000,-480.000000,1.538621e+12
75%,3.300000,0.177250,5.000000,159.000000,1.900000,4.570000,25.000000,0.590000,56.000000,1.538766e+12,0.000000,-480.000000,1.539110e+12
max,8.400000,53.737000,580.000000,355.910000,7.500000,9.120000,172.000000,1.910000,2015.000000,1.539475e+12,1.000000,720.000000,1.539537e+12

In [ ]:
df.alert.unique() #Valores únicos na coluna alert

array([nan, 'green', 'red'], dtype=object)

In [ ]:
df['alert'].value_counts() #quantidade dos valores únicos da coluna alerta

alert
green    58
red       1
Name: count, dtype: int64

In [ ]:
df['mag'] #Seleciona uma coluna

0       1.35
1       1.29
2       3.42
3       0.44
4       2.16
        ...
9327    0.62
9328    1.00
9329    2.40
9330    1.10
9331    0.66
Name: mag, Length: 9332, dtype: float64

In [16]:
df[['mag', 'title']]

       mag                                     title
0     1.35             M 1.4 - 9km NE of Aguanga, CA
1     1.29             M 1.3 - 9km NE of Aguanga, CA
2     3.42             M 3.4 - 8km NE of Aguanga, CA
3     0.44             M 0.4 - 9km NE of Aguanga, CA
4     2.16             M 2.2 - 10km NW of Avenal, CA
...    ...                                       ...
9327  0.62      M 0.6 - 9km ENE of Mammoth Lakes, CA
9328  1.00               M 1.0 - 3km W of Julian, CA
9329  2.40  M 2.4 - 35km NNE of Hatillo, Puerto Rico
9330  1.10             M 1.1 - 9km NE of Aguanga, CA
9331  0.66             M 0.7 - 9km NE of Aguanga, CA

[9332 rows x 2 columns]

In [ ]:
df[100:103] #Slice para os índices [inclusivo:exclusivo]

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
100,NaN,NaN,20280310,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ak20280310,",1.20,ml,...,",ak,",automatic,1539435449480,"M 1.2 - 25km NW of Ester, Alaska",0,earthquake,",geoserve,origin,",-540.0,1539443551010,https://earthquake.usgs.gov/earthquakes/eventp...
101,NaN,NaN,73096756,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01355,NaN,185.0,",nc73096756,",0.59,md,...,",nc,",automatic,1539435391320,"M 0.6 - 8km ESE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539439802162,https://earthquake.usgs.gov/earthquakes/eventp...
102,NaN,NaN,37388730,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.02987,NaN,39.0,",ci37388730,",1.33,ml,...,",ci,",automatic,1539435293090,"M 1.3 - 8km ENE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1539435940470,https://earthquake.usgs.gov/earthquakes/eventp...

In [ ]:
df[['mag', 'title']][100:103] #slice das linhas das colunas mag e title [inclusivo:exclusivo]

      mag                                 title
100  1.20      M 1.2 - 25km NW of Ester, Alaska
101  0.59  M 0.6 - 8km ESE of Mammoth Lakes, CA
102  1.33        M 1.3 - 8km ENE of Aguanga, CA

In [ ]:
#df.loc['row_indexer', 'column_name']
df.loc[110:112, 'title']

110               M 1.1 - 35km S of Ester, Alaska
111    M 1.9 - 93km WNW of Arctic Village, Alaska
112      M 0.9 - 20km WSW of Smith Valley, Nevada
Name: title, dtype: object

In [ ]:
df.loc[10:15, ['title', 'mag']]

                                                title   mag
10                     M 0.5 - 10km NE of Aguanga, CA  0.50
11  M 2.8 - 53km SE of Punta Cana, Dominican Republic  2.77
12                      M 0.5 - 9km NE of Aguanga, CA  0.50
13         M 4.5 - 120km SSW of Banda Aceh, Indonesia  4.50
14                   M 2.1 - 14km NW of Parkfield, CA  2.13
15       M 2.0 - 156km WNW of Haines Junction, Canada  2.00

In [ ]:
#df.iloc['row_indexer', 'column_indexer']
df.iloc[10:15, [19,8]]

                                                title   mag
10                     M 0.5 - 10km NE of Aguanga, CA  0.50
11  M 2.8 - 53km SE of Punta Cana, Dominican Republic  2.77
12                      M 0.5 - 9km NE of Aguanga, CA  0.50
13         M 4.5 - 120km SSW of Banda Aceh, Indonesia  4.50
14                   M 2.1 - 14km NW of Parkfield, CA  2.13

In [25]:
df.iloc[10:15, 6:10]

      gap             ids   mag magType
10   57.0    ,ci37389162,  0.50      ml
11  186.0  ,pr2018286010,  2.77      md
12   76.0    ,ci37389146,  0.50      ml
13  157.0    ,us1000hbti,  4.50      mb
14   71.0    ,nc73096921,  2.13      md

In [ ]:
df['mag'] > 2 #serie booleana

0       False
1       False
2        True
3       False
4        True
        ...
9327    False
9328    False
9329     True
9330    False
9331    False
Name: mag, Length: 9332, dtype: bool

In [29]:
df[df['mag'] >= 7]

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
837,green,4.1,1000haa3,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.763,3.0,14.0,",us1000haa3,pt18283003,at00pgehsk,",7.0,mww,...,",us,pt,at,",reviewed,1539204500290,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake,",dyfi,finite-fault,general-text,geoserve,groun...",600.0,1539378744253,https://earthquake.usgs.gov/earthquakes/eventp...
5263,red,8.4,1000h3p4,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.589,18.0,27.0,",us1000h3p4,us1000h4p4,",7.5,mww,...,",us,us,",reviewed,1538128963480,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake,",dyfi,finite-fault,general-text,geoserve,groun...",480.0,1539123134531,https://earthquake.usgs.gov/earthquakes/eventp...

In [30]:
df.loc[df['mag'] >= 7, ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']]

,alert,mag,magType,title,tsunami,type
837,green,7.0,mww,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake
5263,red,7.5,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

In [ ]:
df.loc[(df['tsunami'] == 1) & (df['alert'] == 'red'), ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']] #operador & == and == e

,alert,mag,magType,title,tsunami,type
5263,red,7.5,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

In [ ]:
df.loc[(df['tsunami'] == 1) | (df['alert'] == 'red'), ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']] #operador | == or == ou

,alert,mag,magType,title,tsunami,type
36,NaN,5.0,mww,"M 5.0 - 165km NNW of Flying Fish Cove, Christm...",1,earthquake
118,green,6.7,mww,"M 6.7 - 262km NW of Ozernovskiy, Russia",1,earthquake
501,green,5.6,mww,"M 5.6 - 128km SE of Kimbe, Papua New Guinea",1,earthquake
799,green,6.5,mww,"M 6.5 - 148km S of Severo-Kuril'sk, Russia",1,earthquake
816,green,6.2,mww,"M 6.2 - 94km SW of Kokopo, Papua New Guinea",1,earthquake
...,...,...,...,...,...,...
8561,NaN,5.4,mb,"M 5.4 - 228km S of Taron, Papua New Guinea",1,earthquake
8624,NaN,5.1,mb,"M 5.1 - 278km SE of Pondaguitan, Philippines",1,earthquake
9133,green,5.1,ml,"M 5.1 - 64km SSW of Kaktovik, Alaska",1,earthquake
9175,NaN,5.2,mb,"M 5.2 - 126km N of Dili, East Timor",1,earthquake
9304,NaN,5.1,mb,"M 5.1 - 34km NW of Finschhafen, Papua New Guinea",1,earthquake

In [ ]:
df.loc[(df['place'].str.contains('Alaska')) & (df['alert'].notnull()), ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']] 
#Seleciona todos os terremotos no Alasca onde temos um valor diferente de nulo.

,alert,mag,magType,title,tsunami,type
1015,green,5.0,ml,"M 5.0 - 61km SSW of Chignik Lake, Alaska",1,earthquake
1273,green,4.0,ml,"M 4.0 - 71km SW of Kaktovik, Alaska",1,earthquake
1795,green,4.0,ml,"M 4.0 - 60km WNW of Valdez, Alaska",1,earthquake
2752,green,4.0,ml,"M 4.0 - 67km SSW of Kaktovik, Alaska",1,earthquake
3260,green,3.9,ml,"M 3.9 - 44km N of North Nenana, Alaska",0,earthquake
4101,green,4.2,ml,"M 4.2 - 131km NNW of Arctic Village, Alaska",0,earthquake
6897,green,3.8,ml,"M 3.8 - 80km SSW of Kaktovik, Alaska",0,earthquake
8524,green,3.8,ml,"M 3.8 - 69km SSW of Kaktovik, Alaska",0,earthquake
9133,green,5.1,ml,"M 5.1 - 64km SSW of Kaktovik, Alaska",1,earthquake

In [ ]:
df.loc[df['mag'].between(6.5, 7.5), ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']] #Utilizou o método between() entre um valor e outro

,alert,mag,magType,title,tsunami,type
118,green,6.7,mww,"M 6.7 - 262km NW of Ozernovskiy, Russia",1,earthquake
799,green,6.5,mww,"M 6.5 - 148km S of Severo-Kuril'sk, Russia",1,earthquake
837,green,7.0,mww,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake
4363,green,6.7,mww,"M 6.7 - 263km NNE of Ndoi Island, Fiji",1,earthquake
5263,red,7.5,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

In [ ]:
df.loc[df['magType'].isin(['mw', 'mwb']), ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']]
#Utilizando o método isin() para selecionar por serie booleana os valores que possuem mw e mwb na coluna magType e mostras as colunas 'alert', 'mag', 'magType', 'title', 'tsunami', 'type' das linhas dos valores True para a presença de mw e mwb

,alert,mag,magType,title,tsunami,type
995,NaN,3.35,mw,"M 3.4 - 9km WNW of Cobb, CA",0,earthquake
1465,green,3.83,mw,"M 3.8 - 109km WNW of Trinidad, CA",0,earthquake
2414,green,3.83,mw,"M 3.8 - 5km SW of Tres Pinos, CA",1,earthquake
4988,green,4.41,mw,"M 4.4 - 1km SE of Delta, B.C., MX",1,earthquake
6307,green,5.80,mwb,"M 5.8 - 297km NNE of Ndoi Island, Fiji",0,earthquake
8257,green,5.70,mwb,"M 5.7 - 175km SSE of Lambasa, Fiji",0,earthquake

In [ ]:
df.loc[[df['mag'].idxmin(), df['mag'].idxmax()], ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']]
#selecionar o índice do valor mínimo e valor máximo e mostrando as colunas 'alert', 'mag', 'magType', 'title', 'tsunami', 'type'

,alert,mag,magType,title,tsunami,type
2409,NaN,-1.26,ml,"M -1.3 - 41km ENE of Adak, Alaska",0,earthquake
5263,red,7.50,mww,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake

In [ ]:
df['source'] = 'USGS API' #Foi criada uma coluna com o mesmo valor
df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,source
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,USGS API
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,USGS API
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,USGS API
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,USGS API
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,USGS API

In [39]:
df['mag_negative'] = df['mag'] < 0
df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,time,title,tsunami,type,types,tz,updated,url,source,mag_negative
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,USGS API,False
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,USGS API,False
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,USGS API,False
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,USGS API,False
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,USGS API,False